timeout: 3600s
tags:
  - open-node-platform
  - snapshot
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: "build-install-image"
  entrypoint: bash
  args:
    - -c
    - |
      gcloud builds submit --config=build-image/cloudbuild.yaml --substitutions=_PROJECT_ID=${_PROJECT_ID}

- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "create-snapshot"
  dir: "create-snapshot"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      NOW=$(date +"%m-%d-%Y")
      snapshot_name="snapshot.$NOW"
      kubectl apply -f - <<EOF
      apiVersion: snapshot.storage.k8s.io/v1beta1
      kind: VolumeSnapshot
      metadata:
        name: $$snapshot_name
      spec:
        volumeSnapshotClassName: snapshot-class
      source:
        persistentVolumeClaimName: full-node-geth-claim
      EOF
  waitFor:
    - build-install-image
