timeout: 3600s # 1-hr
tags:
  - open-node-platform
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _NODE_NAME: ${NODE_NAME}
  _CLUSTER_NAME: ${CLUSTER_NAME}
  _CHAIN_NAME: ${CHAIN_NAME}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "add-node"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}

      if [ $_CHAIN_NAME = "geth" ]
      then
        sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chain/geth/deployment.yaml
        sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chain/geth/pvc.yaml
        sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chain/geth/service.yaml

        kubectl apply -f chain/geth/pvc.yaml
        kubectl apply -f chain/geth/deployment.yaml
        kubectl apply -f chain/geth/service.yaml
      elif [ $_CHAIN_NAME = "polkdot" ]
      then
        sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chain/polkdot/deployment.yaml
        sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chain/polkdot/pvc.yaml
        sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chain/polkdot/service.yaml

        kubectl apply -f chain/polkdot/pvc.yaml
        kubectl apply -f chain/polkdot/deployment.yaml
        kubectl apply -f chain/polkdot/service.yaml
      fi
