timeout: 3600s
tags:
  - open-node-platform
  - snapshot
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _NODE_NAME: ${NODE_NAME}
  _CLUSTER_NAME: ${CLUSTER_NAME}
steps:

- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "create-snapshot"
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}
      NOW=$(date +"%m-%d-%Y")
      # sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" snapshot.yaml
      # sed -i'' -e  "s/TIME/${NOW}/g" snapshot.yaml
      kubectl apply -f snapshot/deployment.yaml
