apiVersion: v1
kind: Service
metadata:
  name: YOUR_NODE_NAME-service
spec:
  type: LoadBalancer
  selector:
    app: YOUR_NODE_NAME
  ports:
  - name: p2p-port
    port: 30303
    protocol: TCP
    targetPort: 30303
  - name: rpc-port
    port: 8545
    protocol: TCP
    targetPort: 8545
