timeout: 3600s # 1-hr
tags:
  - open-node-platform
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _NODE_NAME: ${NODE_NAME}
  _CLUSTER_NAME: ${CLUSTER_NAME}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "add-node"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}

      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chainsnap/geth/deployment.yaml
      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chainsnap/geth/pvc.yaml
      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" chainsnap/geth/service.yaml

      kubectl apply -f chainsnap/geth/pvc.yaml
      kubectl apply -f chainsnap/geth/deployment.yaml
      kubectl apply -f chainsnap/geth/service.yaml
