apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: YOUR_NODE_NAME-snap-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 2000Gi
