timeout: 3600s # 1-hr
tags:
  - open-node-platform
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _NODE_NAME: ${NODE_NAME}
  _CLUSTER_NAME: ${CLUSTER_NAME}
  _CHAIN_NAME: ${CHAIN_NAME}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "add-etl"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}

      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" etl/deployment.yaml
      sed -i'' -e  "s/YOUR_PROJECT/${_PROJECT_ID}/g" etl/deployment.yaml
      
      export FULL_NODE_SVC_NAME=$_NODE_NAME-service
      export FULL_NODE_IP=$(kubectl get svc $$FULL_NODE_SVC_NAME -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
      sed -i'' -e  "s/IP_ADDR/$${FULL_NODE_IP}/g" etl/deployment.yaml


      gcloud pubsub topics create crypto_ethereum.blocks
      gcloud pubsub subscriptions create crypto_ethereum.blocks.test --topic=crypto_ethereum.blocks
      gcloud pubsub topics create crypto_ethereum.transactions
      gcloud pubsub subscriptions create crypto_ethereum.transactions.test --topic=crypto_ethereum.transactions
      kubectl apply -f etl/deployment.yaml
      
      
