timeout: 3600s # 1-hr
tags:
  - open-node-platform
substitutions:
  _PROJECT_ID: ${PROJECT_ID}
  _GCP_REGION: ${GCP_REGION}
  _NODE_NAME: ${NODE_NAME}
  _CLUSTER_NAME: ${CLUSTER_NAME}
  _CHAIN_NAME: ${CHAIN_NAME}
options:
  substitution_option: 'ALLOW_LOOSE'
steps:
- name: "gcr.io/${_PROJECT_ID}/open-node-platform-installer"
  id: "add-etl"
  entrypoint: 'bash'
  args:
    - '-xe'
    - '-c'
    - |
      
      gcloud container clusters get-credentials ${_CLUSTER_NAME} --region ${_GCP_REGION}
      # IP=$(kubectl get service ${"${_NODE_NAME}-service"}--output yaml  | grep 'ip:    ' | sed  "s/- ip:    //g")

      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" etl/deployment.yaml
      
      sed -i'' -e  "s/YOUR_PROJECT/${_PROJECT_ID}/g" etl/deployment.yaml
      
      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" etl/pvc.yaml
      sed -i'' -e  "s/YOUR_NODE_NAME/${_NODE_NAME}/g" etl/service.yaml
      sed -i'' -e  "s/IP_ADDR/$(kubectl get service ${_NODE_NAME}-service --output yaml  |  grep 'ip:' | sed  "s/    - ip: //g")/g" etl/deployment.yaml
      # kubectl apply -f etl/pvc.yaml
      # gcloud pubsub topics create crypto_ethereum.blocks
      # gcloud pubsub subscriptions create crypto_ethereum.blocks.test --topic=crypto_ethereum.blocks
      # gcloud pubsub subscriptions create crypto_ethereum.blocks.test --topic=crypto_ethereum.transactions
      kubectl apply -f etl/deployment.yaml
      # kubectl apply -f etl/service.yaml
      
      
