tags:
  - open-node-platform
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-installer-image'
  args:
  - --destination=gcr.io/${_PROJECT_ID}/open-node-platform-installer
  - --cache=true
  - --cache-ttl=12h
