apiVersion: apps/v1
kind: Deployment
metadata:
  name: YOUR_NODE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: YOUR_NODE_NAME
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: YOUR_NODE_NAME
        type: full
    spec:
      containers:
      - name: platon-node
        image: "gcr.io/g-hash-community/platon-node:v1"
        imagePullPolicy: Always
        ports:
        - name: p2p-port
          containerPort: 16789
        - name: rpc-port
          containerPort: 6789
        volumeMounts:
        - mountPath: /root/platon-node/data/
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: YOUR_NODE_NAME-claim
