apiVersion: v1
kind: Service
metadata:
  name: YOUR_NODE_NAME-service
spec:
  type: LoadBalancer
  selector:
    app: YOUR_NODE_NAME
  ports:
  - name: p2p-port
    port: 16789
    protocol: TCP
    targetPort: 16789
  - name: rpc-port
    port: 6789
    protocol: TCP
    targetPort: 6789
